version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - client
